GET http://localhost:3000/tasks

###
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "title": "Comprar frango"
}

###
PUT http://localhost:3000/tasks/fc653911-cc51-4e13-b11a-bb0043269a8b
Content-Type: application/json

{
    "done": true
}

###
DELETE http://localhost:3000/tasks/4


###
POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Renan",
    "email": "renan@gmail.com",
    "password": "123456"
}

### 
POST http://localhost:3000/login
Content-Type: application/json
Authorization: Bearer string_de_acesso_valido

{
    "email": "renan@gmail.com",
    "password": "123456"
}

###
GET http://localhost:3000/users
